config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('tienda.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    

tienda/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView, LogoutView

app_name='tienda'

urlpatterns = [
    # paths menú
    path('', views.index, name='index'),
    path('categorias/', views.listCategorias, name='categorias'),
    path('contacto/', views.contacto, name='contacto'),
    path('garantia/', views.garantia, name='garantia'),
    path('devoluciones/', views.devoluciones, name='devoluciones'),
    path('nosotros/', views.nosotros, name='nosotros'),

    path('producto/', views.detalleProducto, name='producto'),
    path('addproducto/', views.addProducto, name='addproducto'),
    path('detalleproducto/<id>/', views.detalleProducto, name='detalleproducto'),
    path('productocategoria/<id>/', views.productoxCategoria, name='productocategoria'),
    path('editproducto/<id>/', views.editarProducto, name='editproducto'),
    path('deleteProducto/<id>/', views.deleteProducto, name='deleteProducto'),
    path('listarproductos/', views.listarProductos, name='listarproductos'),
    path('addcategoria/', views.addCategoria, name='addcategoria'),
    path('editcategoria/<id>/', views.modificarCategoria, name='editcategoria'),
    path('deleteCategoria/<id>/', views.deleteCategoria, name='deleteCategoria'),
        
    # paths de autenticacion
    path('registrar/', views.registrar, name='registrar'),
    path('login/', LoginView.as_view(template_name='auth/login.html'), name='login'),
    
    #Paths del carrito
    path('viewcart/', views.viewcart, name="viewcart"),

    path('addcart/<producto_id>/', views.agregar_producto, name="addcart"),

    path('delcart/<producto_id>/', views.eliminar_producto, name="delcart"),

    path('restarcart/<producto_id>/', views.restar_producto, name="restarcart"),

    path('cleancart/', views.cleancart, name="cleancart"),

    path('procesar_compra/', views.procesar_compra, name="procesar_compra"),
    
]

templates/categorias.html
{% extends 'layouts/tienda.html' %} {% block content %}
<div class="min-vh-100 d-flex flex-colum py-4">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-8 col-md-6 col-sm-4 animate__animated animate__backInRight animate__delay-0.4s">
                <div class="card">
                    <div class="card-header text-center font-weight-bold">
                        {{ title }}
                    </div>
                    <div class="card-body  table-responsive">
                        <div class="d-flex justify-content-end mb-2 mx-2">
                            <a href="/addcategoria" class="btn btn-dark btn-sm pull-right" type="submit">
                            Nueva Categoria
                            </a>
                        </div>
                        <table class="table table-condensed">
                            <thead class="thead-dark">
                                <tr class="text-center">
                                    <th scope="col">#</th>
                                    <th scope="col">Nombre</th>
                                    <th colspan="2">Opciones</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% load bootstrap_icons %} {% if entity %} {% for categoria in entity %}
                                <tr>
                                    <td>{{ categoria.id }}</td>
                                    <td>{{ categoria.nombre }}</td>
                                    <td colspan="2" class="text-center">
                                        <a class="btn btn-secondary btn-sm" href="{% url 'tienda:editcategoria' categoria.id %}" type="button"><i class="bi bi-pencil-square"></i></a>
                                        <a class="btn btn-danger btn-sm" href="{% url 'tienda:deleteCategoria' categoria.id %}" type="button"><i class="bi bi-trash-fill"></i></a>
                                    </td>
                                </tr>
                                {% endfor %} {% else %}
                                <div class="text-center text-warning">
                                    <h3> No se encontraron Productos!!</h3>
                                </div>
                                {% endif %}
                            </tbody>
                        </table>
                        <div>
                            {% include 'paginator.html' %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/contacto.html
{% extends 'layouts/tienda.html' %} {% block content %}

<div class="min-vh-100 d-flex flex-colum py-4">
    <div class="container">
        <h3 class="animate__animated animate__bounceInDown animate__delay-0.2s text-center">CONTACTO</h3>
        <div class="row">
            <div class="col-lg-6 col-sm-04 mx-auto animate__animated animate__bounceInUp animate__delay-0.3s">
                {% load crispy_forms_tags %}
                <form method="post" action="">
                    {% csrf_token %} {{ form | crispy }}
                    <div class="justify-content-center">
                        <button type="reset" class="btn btn-secondary mt-1 mx-2" button ">Cancelar</button>
                        <button type="submit " class="btn btn-danger mt-1 " button ">Enviar</button>
                    </div>
                </form>
            </div>
            <div class="col-lg-6 col-sm-04 mt-4 rounded animate__animated animate__backInRight animate__delay-0.4s embed-responsive embed-responsive-4by3">
                <iframe class="embed-responsive-item" src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d14430.562074791773!2d-57.5631911958008!3d-25.28267551710696!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x945da8a71743dd1f%3A0x8a4f04a444d5c487!2sAvenida%20Aviadores%20del%20Chaco%2C%20Asunci%C3%B3n!5e0!3m2!1ses-419!2spy!4v1625278377323!5m2!1ses-419!2spy"
                    style="border:0;" allowfullscreen="" loading="lazy"></iframe>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/devoluciones.html
{% extends 'layouts/tienda.html' %}{% load static %} {% block content %}

<div class="min-vh-100 d-flex flex-colum py-2">
    <div class="container">
        <h3 class="animate__animated animate__bounceInDown animate__delay-0.3s text-center py-4">DEVOLUCIONES</h3>
        <div class="row py-auto">
            <div class="col-10 mx-auto animate__animated animate__backInRight animate__delay-0.3s ">
                <p class="text-justify">
                    Si el producto entregado al Cliente fuese diferente al solicitado, el mismo Cliente podrá desistir de la compra, y JAGUARETE KAA S.A. procederá a la devolución de valor abonado por este. El Cliente dispone de 5 dias hábiles posterior a la entrega para
                    realizar el reclamo correspondiente. </p>
                <p class="text-justify">El orden de reembolso se realizará dentro de las 48 horas hábiles siguientes al reclamo del Cliente, y se hará efectiva a la cuenta de este según las políticas de las operadoras de tarjetas de crédito.
                </p>
                <p class="text-justify">
                    <span class="font-weight-bold"> Observación:</span> En ningún caso se prodrá proceder a realizar reembolso por un medio diferente al empleado para el pago. En todos los casos se deberá conservar la factura de compra.
                </p>
                <div class="col-10 text-right">
                    <a href="/" class="btn btn-dark my-4 mx-auto">Atras</a>
                </div>
            </div>
        </div>

    </div>
</div>

{% endblock %}

templates/garantia.html
{% extends 'layouts/tienda.html' %}{% load static %} {% block content %}

<div class="min-vh-100 d-flex flex-colum py-2">
    <div class="container">
        <h3 class="animate__animated animate__bounceInDown animate__delay-0.3s text-center py-4">GARANTIA</h3>
        <div class="row py-auto">
            <div class="col-10 mx-auto animate__animated animate__backInRight animate__delay-0.3s">
                <p class="text-justify">
                    Todos los productos de nuestra distribución tienen garantía. Estas oscilan entre 6 meses a 3 años inclusive, dependiendo de las marcas, los productos y de ciertos componentes de los mismos. Las garantías son cubiertas por los representantes de cada marca,
                    quiénes a través de sus servicios autorizados informan sobre los productos que ingresan al mismo y las condiciones de las garantías. La garantía no significa cambio de mercaderías: La garantía incluye en todos los casos, mano de obra
                    y ajustes sin cargo alguno; además de los repuestos que presenten fallas o averías de origen. No así, las carcasas o los vidrios rotos, la chapería golpeada y el mal uso del producto en general, como tampoco las roturas de engranajes
                    por sobrecarga, el rotor, etc. La garantía no cubre las fallas, cuando estas son a causa de fenómenos naturales, como terremotos, inundaciones, tormentas eléctricas, etc.; o por situaciones accidentales o provocadas por incendios,
                    fluctuaciones de voltaje o corriente, robos; como tampoco cuando las mercaderías presenten adulteración del número de serie.
                </p>
                <p class="text-justify font-weight-bold">El derecho que otorga la garantía, queda automáticamente anulado: </p>
                <p class="text-justify">
                    1º Si el producto presenta señales evidentes de haber sido revisado por personal no autorizado por el representante.
                </p>

                <p class="text-justify">2º Por el solo hecho de haberse conectado a una corriente distinta a la indicada en el producto, o presentar señales de haber recibido una descarga eléctrica.
                </p>

                <p class="text-justify">
                    3º Si presenta señales evidentes de maltrato, golpes, caídas o uso indebido. O en los casos que los productos lleguen al taller sin las estampillas de garantías del proveedor.
                </p>
                <p class="text-justify">Precauciones al momento de recibir la mercadería Rogamos su completa revisión ya que los cambios de mercaderías con fallas o averías, solo se realizarán en los casos de reclamos recibidos dentro de las 48 horas siguientes a la recepción
                    de los productos, siempre y cuando se traten de defectos de fabricación.
                </p>
                <p class="text-justify"><span class="font-weight-bold">En el caso de los artículos electrónicos, será necesario un informe técnico previo</span>, de forma a determinar si el defecto proviene de origen, o fue a causa de la variación en la tensión de la corriente
                    eléctrica. Si su producto requiere instalación o enseñanza de uso y manejo para su correcta utilización, tenga la gentileza de llamar al Departamento de Servicio Técnico de Casa Central +595 981 962 250.
                </p>
            </div>
            <div class="col-10 text-right">
                <a href="/" class="btn btn-dark my-4 mx-auto">Atras</a>
            </div>
        </div>

    </div>
</div>

{% endblock %}

templates/index.html
{% extends "layouts/tienda.html" %} {% load static %} {% block content %}
<div class="min-vh-100 d-flex flex-colum pb-3">
    <div class="container">

        <!-- Header-->
        <header class="bg-dark py-3 rounded-bottom animate__animated animate__zoomIn animate__delay-0.3s">
            <div class="text-center text-white ">
                <h1 class="display-4 fw-bolder animate__animated animate__bounceInDown animate__delay-0.4s">Estamos con increibles Ofertas</h1>
                <h4 class="lead fw-normal mb-0 animate__animated animate__rollIn animate__delay-0.7s">hasta 45% off!</h4>
            </div>
        </header>

        <!-- Section-->
        <div class="pt-3">
            <form class="d-flex d-md-inlne-block form-inline justify-content-end" method="POST" action="">
                {% csrf_token %}
                <div class="input-group">
                    <input type="text" class="form-control bg-light border-1 small text-center" name="buscador" placeholder="buscar..." value="{{ request.POST.buscador }}">
                    <div class="input-group-append">
                        <button class="btn btn-danger mx-1" type="submit"> 
                    <i class="bi bi-search bi-sm"></i>
                </button>
                    </div>
                </div>
            </form>
        </div>

        <section class="py-2">
            <div class="container px-4 px-lg-5 mt-2 animate__animated animate__fadeIn animate__delay-0.3s">
                <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
                    {% if entity %} {% for producto in entity %}
                    <div class="col my-3">
                        <div class="card h-100 text-center py-3">
                            <!-- Product image-->
                            {% if producto.imagen %}
                            <img class="mx-auto d-block img-fluid" src="{{ producto.imagen.url }}" alt="producto" width="60px%" /> {% else %}
                            <img class="card-img-top" src="https://dummyimage.com/450x300/dee2e6/6c757d.jpg" alt="sinImagen" /> {% endif %}
                            <!-- Product details-->
                            {% load humanize %}
                            <div class="card-body p-3">
                                <div class="text-center">
                                    <!-- Product name-->
                                    <h5 class="fw-bolder">{{ producto.nombre }}</h5>
                                    <!-- Product price-->
                                    Gs. {{ producto.precio | intcomma }}
                                </div>
                            </div>
                            <!-- Product actions-->
                            <div class="card-footer p-2 pt-2 border-top-0 bg-transparent">
                                <div class="text-center">
                                    <a class="btn btn-dark mt-auto" href="{% url 'tienda:detalleproducto' producto.id %}">Ver detalle</a> {% if user.is_authenticated%}
                                    <a href="{% url 'tienda:addcart' producto.id %}" class="btn btn-danger mt-2" type="button">
                                        <i class="bi-cart-fill me-1"></i> Agregar al Carrito
                                    </a>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endfor %} {% else %}
                    <div class="text-center text-warning">
                        <h3> No se encontraron Productos!!</h3>
                    </div>
                    {% endif %}
                </div>

                <div>
                    {% include 'paginator.html' %}
                </div>
            </div>

        </section>
    </div>
</div>
{% endblock %}

templates/nosotros.html
{% extends 'layouts/tienda.html' %}{% load static %} {% block content %}

<div class="min-vh-100 d-flex flex-colum py-2">
    <div class="container">
        <h3 class="animate__animated animate__bounceInDown animate__delay-0.3s text-center py-4">JAGUARETE KAA S.A.</h3>
        <div class="row py-auto">
            <div class="col-lg-8">
                <p class="animate__animated animate__backInRight animate__delay-0.3s text-justify">
                    Somos una empresa joven, enfocada en el cliente, con servicios innovadores de tecnología a nivel nacional e internacional. Jaguarete Ka'a surge con la idea de ofrecer productos útiles y novedosos en internet al público en general. Queremos ayudarte a
                    potenciar el crecimiento tecnológico de tu empresa, cuando tu empresa crece, tus clientes crecen. Desde 2015 promovemos y generamos servicios de plataformas y contenidos digitales, 6 años creciendo y alcanzando nuevas metas con nuestros
                    clientes.
                </p>
                <p class="animate__animated animate__backInRight animate__delay-0.3s text-justify">
                    No existe un negocio de e-commerce que sea igual a otro en Paraguay, por lo que la oportunidad estaba latente y era clave aprovecharla en el tiempo indicado. Con la masificación del acceso a internet y la globalización de los mercados, el e-commerce es
                    la alternativa de compras del futuro. En Paraguay el rubro también está creciendo actualmente por lo que es importante apostar por el crecimiento económico y tecnológico del sector.
                </p>
            </div>

            <div class="col-lg-4 animate__animated animate__bounceInUp animate__delay-0.4s ">
                <img class="img-fluid ml-auto" src="{% static 'assets/team.jpg' %}" alt="team">
            </div>

        </div>
        <div class="row animate__animated animate__bounceInUp animate__delay-1s">
            <p class="mb-1">Teléfono: +595 981 962 250 | +595 981 550 695</p>
            <p> Asunción, Paraguay</p>
        </div>
    </div>
</div>

{% endblock %}

templates/paginator.html
{% if paginator.num_pages > 1 %}
    
    <div class="d-flex justify-content-center">
        <ul class="pagination">
            {% if entity.has_previous %}
                <li class="page-item d-none d-sm-block">
                    <a class="page-link" href="?page={{ entity.previous_page_number }}#pagtable">Anterior</a>
                </li>
            {% endif %} 

            {% for page in paginator.page_range %} 
                {% if forloop.last and page != entity.number and paginator.num_pages > 7 %} 
                    {% if entity.next_page_number != paginator.num_pages%}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ entity.number | add:1}}#pagtable">...</a>
                        </li>
                    {% endif %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ paginator.num_pages }}#pagtable">
                            {{paginator.num_pages}}
                        </a>
                    </li>
                {% endif %} 

                {% if page == entity.number and page > 7 %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page | add:-1 }}#pagtable">...</a>
                    </li>
                {% endif %} 

                {% if page < 7 or page == entity.number %} 
                    <li class="page-item {% if page == entity.number %} active{% endif %}">
                        <a class="page-link" href="?page={{ page }}#pagtable">{{ page }}</a>
                    </li>
                {% endif %} 
            {% endfor %} 

            {% if entity.has_next %}
                <li class="page-item d-none d-sm-block">
                    <a class="page-link" href="?page={{ entity.next_page_number }}#pagtable">Siguiente</a>
                </li>
            {% endif %}
        </ul>
    </div>

    <div class="d-flex justify-content-center d-sm-none">
        {% if entity.has_previous %}
            <span class="page-item"><a  class="page-link" href="?page={{ entity.previous_page_number }}#pagtable">Anterior</a></span> 
        {% endif %} 

        {% if entity.has_next %}
            <span class="page-item"><a class="page-link" href="?page={{ entity.next_page_number }}#pagtable">Siguiente</a></span> 
        {% endif %}
            <br>
            <br>
    </div>
    
{% endif %}